//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastDeliveryBE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastDeliveryBE.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة مضافة سابقاً.
        /// </summary>
        public static string AddDepartment_AlreadyExist {
            get {
                return ResourceManager.GetString("AddDepartment-AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة المفوض , المفوض مضاف مسبقاً.
        /// </summary>
        public static string AddDepartmentsApprovalDelegation_AlreadyExist {
            get {
                return ResourceManager.GetString("AddDepartmentsApprovalDelegation-AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة اعتماد إدارة موجود مسبقاً.
        /// </summary>
        public static string AddDepartmentsApprovalLevel_AlreadyExist {
            get {
                return ResourceManager.GetString("AddDepartmentsApprovalLevel-AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف مضاف سابقاً على الهيكل التنظيمي.
        /// </summary>
        public static string AddUser_AlreadyExist {
            get {
                return ResourceManager.GetString("AddUser-AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الموظف غير متوفرة على النظام.
        /// </summary>
        public static string ChangeEmployeeDepartment_NotExist {
            get {
                return ResourceManager.GetString("ChangeEmployeeDepartment-NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استرجاع البيانات.
        /// </summary>
        public static string DataSelected {
            get {
                return ResourceManager.GetString("DataSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة غير موجودة في قاعدة البيانات.
        /// </summary>
        public static string DeleteDepartment_NotExist {
            get {
                return ResourceManager.GetString("DeleteDepartment-NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن حذف المفوض , لم يتمكن النظام من إيجاد بياناته.
        /// </summary>
        public static string DeleteDepartmentsApprovalDelegation_NotExist {
            get {
                return ResourceManager.GetString("DeleteDepartmentsApprovalDelegation-NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكنك حذف آلية اعتماد غير موجودة.
        /// </summary>
        public static string DeleteDepartmentApprovalLevel_NotExist {
            get {
                return ResourceManager.GetString("DeleteDepartmentApprovalLevel-NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت العملية.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن تعديل مدير الإدارة , لم يتمكن النظام من إيجاد بيانات الإدارة.
        /// </summary>
        public static string SetDepartmentManager_DepartmentNotExist {
            get {
                return ResourceManager.GetString("SetDepartmentManager-DepartmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن تعديل مدير الإدارة : بيانات المدير غير صحيحة .
        /// </summary>
        public static string SetDepartmentManager_EmployeeNotExist {
            get {
                return ResourceManager.GetString("SetDepartmentManager-EmployeeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تحديث بيانات الموظف , لم يتمكن النظام من إيجاد بياناته.
        /// </summary>
        public static string UpdateUser_NotExist {
            get {
                return ResourceManager.GetString("UpdateUser-NotExist", resourceCulture);
            }
        }
    }
}
